FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Előbb csak a pom.xml-t másoljuk, hogy a dependency-k cache-elve legyenek
# (gyorsabb újraépítés, ha csak a teszt kódot módosítod)
COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY test ./test

CMD ["mvn", "-B", "test"]